In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('data/manhattan_jan_time.csv')

In [3]:
data.columns

Index([u'pickup_datetime', u'pickup_latitude', u'pickup_longitude',
       u'trip_distance', u'passenger_count', u'dropoff_datetime',
       u'dropoff_latitude', u'dropoff_longitude', u'fare_amount',
       u'tolls_amount', u'taxes_amount', u'tip_amount', u'payment_amount',
       u'payment_type', u'pickup_neighborhood', u'dropoff_neighborhood',
       u'pickups_place', u'dropoff_place', u'dummy', u'pick_day',
       u'pick_weekday', u'time', u'pick_hour', u'weekgroup'],
      dtype='object')

In [4]:
data.columns

Index([u'pickup_datetime', u'pickup_latitude', u'pickup_longitude',
       u'trip_distance', u'passenger_count', u'dropoff_datetime',
       u'dropoff_latitude', u'dropoff_longitude', u'fare_amount',
       u'tolls_amount', u'taxes_amount', u'tip_amount', u'payment_amount',
       u'payment_type', u'pickup_neighborhood', u'dropoff_neighborhood',
       u'pickups_place', u'dropoff_place', u'dummy', u'pick_day',
       u'pick_weekday', u'time', u'pick_hour', u'weekgroup'],
      dtype='object')

In [5]:
def Entropy(data, cuadrant):
    grid = data.loc[ (data['pickups_place']==cuadrant) ,['dropoff_place','dummy']]    
    # Get the total amount of rides (not unique) in that time period
    totalrides = grid['dummy'].sum()
    # Make a DataFrame called entropy that has the freq of each dropof destination
    entropy = pd.DataFrame(grid['dropoff_place'].value_counts())
    entropy['freq']  =entropy['dropoff_place']
    entropy.drop('dropoff_place', axis=1, inplace=True)
    #calculate probability as freq(x)/Totalrides
    entropy['prob'] = entropy['freq']/totalrides
    import math
    # Calculate log(prob)
    entropy['log_prob'] = entropy['prob'].apply(lambda x:math.log(x,2))
    # Calculate the product of prob *loc(prob)
    entropy['product'] = entropy['prob']*entropy['log_prob']
    # Sum of products times -1 is the entropy value
    Entropy = -1*entropy['product'].sum()
    return Entropy

In [6]:
def SpatialDiversity(data, cuadrant):
    grid = data.loc[ (data['pickups_place']==cuadrant) ,['dropoff_place','dummy']]    
    # Get the total amount of rides (not unique) in that time period
    totalrides = grid['dummy'].sum()
    #
    unique_dropoff_places = grid['dropoff_place'].unique().size
    #print(unique_dropoff_places)
    # Make a DataFrame called entropy that has the freq of each dropof destination
    entropy = pd.DataFrame(grid['dropoff_place'].value_counts())
    entropy['freq']  =entropy['dropoff_place']
    entropy.drop('dropoff_place', axis=1, inplace=True)
    #calculate probability as freq(x)/Totalrides
    entropy['prob'] = entropy['freq']/totalrides
    import math
    # Calculate log(prob)
    entropy['log_prob'] = entropy['prob'].apply(lambda x:math.log(x,2))
    # Calculate the product of prob *loc(prob)
    entropy['product'] = entropy['prob']*entropy['log_prob']
    # Sum of products times -1 is the entropy value
    Entropy = -1*entropy['product'].sum()
    return Entropy/math.log(unique_dropoff_places,2)

In [7]:
def SpatialDiversityIncoming(data, cuadrant):
    grid = data.loc[ (data['dropoff_place']==cuadrant) ,['pickups_place','dummy']]    
    # Get the total amount of rides (not unique) in that time period
    totalrides = grid['dummy'].sum()
    #
    unique_pickup_places = grid['pickups_place'].unique().size
       
    #print("cuadrant: " + cuadrant)
    #print(unique_pickup_places)
    if unique_pickup_places==0:
        return "NaN"
    # Make a DataFrame called entropy that has the freq of each pickup source
    entropy = pd.DataFrame(grid['pickups_place'].value_counts())
    entropy['freq']  =entropy['pickups_place']
    entropy.drop('pickups_place', axis=1, inplace=True)
    #calculate probability as freq(x)/Totalrides
    entropy['prob'] = entropy['freq']/totalrides
    import math
    # Calculate log(prob)
    entropy['log_prob'] = entropy['prob'].apply(lambda x:math.log(x,2))
    # Calculate the product of prob *loc(prob)
    entropy['product'] = entropy['prob']*entropy['log_prob']
    # Sum of products times -1 is the entropy value
    Entropy = -1*entropy['product'].sum()
    return Entropy/math.log(unique_pickup_places,2)

In [8]:
def Entropy2(data, cuadrant, weekgroup, hour):
    grid = data.loc[ (data['pickups_place']==cuadrant)&( data['weekgroup']==weekgroup )&(data['pick_hour']==hour) ,['dropoff_place','dummy']]    
    # Get the total amount of rides (not unique) in that time period
    totalrides = grid['dummy'].sum()
    # Make a DataFrame called entropy that has the freq of each dropof destination
    entropy = pd.DataFrame(grid['dropoff_place'].value_counts())
    entropy['freq']  =entropy['dropoff_place']
    entropy.drop('dropoff_place', axis=1, inplace=True)
    #calculate probability as freq(x)/Totalrides
    entropy['prob'] = entropy['freq']/totalrides
    import math
    # Calculate log(prob)
    entropy['log_prob'] = entropy['prob'].apply(lambda x:math.log(x,2))
    # Calculate the product of prob *loc(prob)
    entropy['product'] = entropy['prob']*entropy['log_prob']
    # Sum of products times -1 is the entropy value
    Entropy = -1*entropy['product'].sum()
    return Entropy

In [9]:
def EntropyDay(data, cuadrant, pick_day, hour):
    grid = data.loc[ (data['pickups_place']==cuadrant)&( data['pick_day']==pick_day )&(data['pick_hour']==hour) ,['dropoff_place','dummy']]    
    # Get the total amount of rides (not unique) in that time period
    totalrides = grid['dummy'].sum()
    # Make a DataFrame called entropy that has the freq of each dropof destination
    entropy = pd.DataFrame(grid['dropoff_place'].value_counts())
    entropy['freq']  =entropy['dropoff_place']
    entropy.drop('dropoff_place', axis=1, inplace=True)
    #calculate probability as freq(x)/Totalrides
    entropy['prob'] = entropy['freq']/totalrides
    import math
    # Calculate log(prob)
    entropy['log_prob'] = entropy['prob'].apply(lambda x:math.log(x,2))
    # Calculate the product of prob *loc(prob)
    entropy['product'] = entropy['prob']*entropy['log_prob']
    # Sum of products times -1 is the entropy value
    Entropy = -1*entropy['product'].sum()
    return Entropy

In [10]:
c = Entropy(data, '4,5')
c

5.6297690639359574

In [11]:
c = Entropy(data, '7,6')
c

5.2102078695719731

In [12]:
c = Entropy(data, '8,6')
c

5.2927267789923835

In [13]:
c = Entropy(data, '3,5')
c

5.9292416665609382

In [14]:
c = Entropy2(data, '4,5', 0, 1)
c

6.2389525120873648

In [15]:
c = Entropy2(data, '4,5', 1, 1)
c

6.0875381192536686

In [16]:
c = Entropy2(data, '4,5', 2, 1)
c

5.7296698211920747

In [17]:
c = Entropy2(data, '4,5', 3, 1)
c

5.6589736161296269

In [18]:
c = EntropyDay(data, '4,5', 1, 1)
c

5.819498025295295

In [19]:
places = pd.DataFrame(data['pickups_place'].unique())

In [20]:
places['place'] = places[0]
places.drop(0, axis=1, inplace=True)
places

     place
0      5,5
1     10,8
2      6,6
3      4,4
4     11,9
5      4,5
6      6,3
7      8,7
8      6,4
9     11,6
10     8,5
11     3,5
12     9,6
13     3,4
14     5,4
15     9,8
16     9,5
17     3,6
18     9,7
19    11,8
20     7,6
21    10,9
22     8,4
23     5,6
24    10,7
25     6,5
26   12,10
27     7,5
28     8,6
29     8,8
..     ...
135   7,13
136   3,11
137   2,12
138   8,13
139   1,13
140   4,13
141   6,13
142  13,13
143   12,6
144   5,10
145  20,12
146   5,12
147    4,7
148  11,11
149  17,13
150   4,11
151   4,12
152    5,9
153    5,8
154   15,8
155  20,11
156  12,13
157  20,13
158   5,13
159   2,13
160    5,7
161   3,13
162  15,13
163  19,10
164    4,2

[165 rows x 1 columns]

In [21]:
places['Entropy'] = places['place'].apply(lambda x: Entropy(data,x))
places

     place   Entropy
0      5,5  5.303888
1     10,8  4.877746
2      6,6  5.165543
3      4,4  5.232075
4     11,9  5.490741
5      4,5  5.629769
6      6,3  5.377346
7      8,7  5.061327
8      6,4  5.239246
9     11,6  5.043993
10     8,5  5.468417
11     3,5  5.929242
12     9,6  5.122434
13     3,4  5.653090
14     5,4  5.338598
15     9,8  5.036826
16     9,5  5.142467
17     3,6  5.327046
18     9,7  4.744064
19    11,8  5.260202
20     7,6  5.210208
21    10,9  5.298749
22     8,4  5.275103
23     5,6  5.182341
24    10,7  4.921153
25     6,5  5.241968
26   12,10  5.551328
27     7,5  5.053708
28     8,6  5.292727
29     8,8  5.147642
..     ...       ...
135   7,13  4.182779
136   3,11  2.521641
137   2,12  4.323231
138   8,13  3.321928
139   1,13  2.584963
140   4,13  2.985228
141   6,13  4.111898
142  13,13  2.251629
143   12,6  3.503258
144   5,10  4.631846
145  20,12  2.235926
146   5,12  4.572182
147    4,7  3.965596
148  11,11  2.842092
149  17,13  1.921928
150   4,11  2.845351
151   4,12  3.565448
152    5,9  3.672906
153    5,8 -0.000000
154   15,8  1.584963
155  20,11 -0.000000
156  12,13  2.750000
157  20,13 -0.000000
158   5,13 -0.000000
159   2,13 -0.000000
160    5,7  2.173557
161   3,13 -0.000000
162  15,13  1.000000
163  19,10  1.584963
164    4,2  1.000000

[165 rows x 2 columns]

In [22]:
places['SpatialDiversity'] = places['place'].apply(lambda x: SpatialDiversity(data,x))
places

     place   Entropy  SpatialDiversity
0      5,5  5.303888          0.588587
1     10,8  4.877746          0.579744
2      6,6  5.165543          0.572526
3      4,4  5.232075          0.596039
4     11,9  5.490741          0.670031
5      4,5  5.629769          0.623215
6      6,3  5.377346          0.614445
7      8,7  5.061327          0.567486
8      6,4  5.239246          0.587434
9     11,6  5.043993          0.619689
10     8,5  5.468417          0.606469
11     3,5  5.929242          0.672969
12     9,6  5.122434          0.594869
13     3,4  5.653090          0.645707
14     5,4  5.338598          0.596991
15     9,8  5.036826          0.568222
16     9,5  5.142467          0.609685
17     3,6  5.327046          0.725770
18     9,7  4.744064          0.576182
19    11,8  5.260202          0.678308
20     7,6  5.210208          0.569754
21    10,9  5.298749          0.622811
22     8,4  5.275103          0.604394
23     5,6  5.182341          0.594698
24    10,7  4.921153          0.632963
25     6,5  5.241968          0.576165
26   12,10  5.551328          0.702087
27     7,5  5.053708          0.564212
28     8,6  5.292727          0.582591
29     8,8  5.147642          0.581540
..     ...       ...               ...
135   7,13  4.182779          0.952294
136   3,11  2.521641          0.975504
137   2,12  4.323231          0.969458
138   8,13  3.321928          1.000000
139   1,13  2.584963          1.000000
140   4,13  2.985228          0.941735
141   6,13  4.111898          0.795350
142  13,13  2.251629          0.969724
143   12,6  3.503258          0.946714
144   5,10  4.631846          0.882605
145  20,12  2.235926          0.962961
146   5,12  4.572182          0.941169
147    4,7  3.965596          0.933537
148  11,11  2.842092          0.727456
149  17,13  1.921928          0.960964
150   4,11  2.845351          0.948450
151   4,12  3.565448          0.936463
152    5,9  3.672906          0.918226
153    5,8 -0.000000               NaN
154   15,8  1.584963          1.000000
155  20,11 -0.000000               NaN
156  12,13  2.750000          0.979570
157  20,13 -0.000000               NaN
158   5,13 -0.000000               NaN
159   2,13 -0.000000               NaN
160    5,7  2.173557          0.774237
161   3,13 -0.000000               NaN
162  15,13  1.000000          1.000000
163  19,10  1.584963          1.000000
164    4,2  1.000000          1.000000

[165 rows x 3 columns]

In [23]:
places['SpatialDiversity-Incoming'] = places['place'].apply(lambda x: SpatialDiversityIncoming(data,x))
places

     place   Entropy  SpatialDiversity SpatialDiversity-Incoming
0      5,5  5.303888          0.588587                  0.678426
1     10,8  4.877746          0.579744                  0.675435
2      6,6  5.165543          0.572526                  0.670329
3      4,4  5.232075          0.596039                  0.690349
4     11,9  5.490741          0.670031                  0.742827
5      4,5  5.629769          0.623215                  0.674619
6      6,3  5.377346          0.614445                  0.702569
7      8,7  5.061327          0.567486                  0.670923
8      6,4  5.239246          0.587434                  0.684967
9     11,6  5.043993          0.619689                  0.700273
10     8,5  5.468417          0.606469                  0.696026
11     3,5  5.929242          0.672969                  0.703419
12     9,6  5.122434          0.594869                   0.69236
13     3,4  5.653090          0.645707                  0.716866
14     5,4  5.338598          0.596991                  0.676921
15     9,8  5.036826          0.568222                  0.670643
16     9,5  5.142467          0.609685                  0.700259
17     3,6  5.327046          0.725770                  0.722495
18     9,7  4.744064          0.576182                  0.672389
19    11,8  5.260202          0.678308                  0.749234
20     7,6  5.210208          0.569754                  0.683641
21    10,9  5.298749          0.622811                  0.705238
22     8,4  5.275103          0.604394                  0.673615
23     5,6  5.182341          0.594698                  0.673137
24    10,7  4.921153          0.632963                  0.713587
25     6,5  5.241968          0.576165                  0.675577
26   12,10  5.551328          0.702087                  0.735747
27     7,5  5.053708          0.564212                  0.674674
28     8,6  5.292727          0.582591                  0.689577
29     8,8  5.147642          0.581540                   0.68595
..     ...       ...               ...                       ...
135   7,13  4.182779          0.952294                  0.821963
136   3,11  2.521641          0.975504                   0.91761
137   2,12  4.323231          0.969458                  0.816592
138   8,13  3.321928          1.000000                  0.849072
139   1,13  2.584963          1.000000                  0.803861
140   4,13  2.985228          0.941735                  0.843278
141   6,13  4.111898          0.795350                   0.81411
142  13,13  2.251629          0.969724                  0.894253
143   12,6  3.503258          0.946714                  0.940924
144   5,10  4.631846          0.882605                  0.881185
145  20,12  2.235926          0.962961                  0.867751
146   5,12  4.572182          0.941169                  0.884931
147    4,7  3.965596          0.933537                  0.938199
148  11,11  2.842092          0.727456                  0.884537
149  17,13  1.921928          0.960964                  0.910475
150   4,11  2.845351          0.948450                  0.877503
151   4,12  3.565448          0.936463                  0.903902
152    5,9  3.672906          0.918226                  0.908344
153    5,8 -0.000000               NaN                         1
154   15,8  1.584963          1.000000                   0.94877
155  20,11 -0.000000               NaN                  0.871764
156  12,13  2.750000          0.979570                  0.854853
157  20,13 -0.000000               NaN                  0.886151
158   5,13 -0.000000               NaN                  0.842609
159   2,13 -0.000000               NaN                  0.856131
160    5,7  2.173557          0.774237                  0.811512
161   3,13 -0.000000               NaN                  0.878291
162  15,13  1.000000          1.000000                  0.914976
163  19,10  1.584963          1.000000                  0.989297
164    4,2  1.000000          1.000000                       NaN

[165 rows x 4 columns]

In [32]:
places = places.sort_values('SpatialDiversity-Incoming', ascending=False)
places

     place   Entropy  SpatialDiversity SpatialDiversity-Incoming
164    4,2  1.000000          1.000000                       NaN
153    5,8 -0.000000               NaN                         1
163  19,10  1.584963          1.000000                  0.989297
133  16,13  1.000000          1.000000                  0.949617
154   15,8  1.584963          1.000000                   0.94877
143   12,6  3.503258          0.946714                  0.940924
147    4,7  3.965596          0.933537                  0.938199
104  19,13  4.035582          0.950012                  0.920459
98   17,12  4.138502          0.957559                  0.920006
136   3,11  2.521641          0.975504                   0.91761
97   16,11  4.124084          0.954223                  0.916472
117  16,12  4.712284          0.960340                  0.915711
162  15,13  1.000000          1.000000                  0.914976
105  14,11  4.925954          0.872799                  0.912318
131  14,13  2.641604          0.940958                  0.911642
103    1,4  3.273367          0.800831                  0.911131
149  17,13  1.921928          0.960964                  0.910475
152    5,9  3.672906          0.918226                  0.908344
129  15,12  4.415552          0.939391                  0.907746
101  15,11  4.900827          0.903168                   0.90584
151   4,12  3.565448          0.936463                  0.903902
77   18,12  4.594222          0.903048                  0.898125
113  14,12  4.916894          0.951057                  0.896139
89   18,13  2.725481          0.970836                  0.894824
142  13,13  2.251629          0.969724                  0.894253
49   13,11  5.047637          0.854534                  0.891622
114   17,9  4.619658          0.900644                   0.88886
157  20,13 -0.000000               NaN                  0.886151
71   13,12  4.566752          0.905312                  0.885423
146   5,12  4.572182          0.941169                  0.884931
..     ...       ...               ...                       ...
64     9,4  4.327214          0.669906                  0.703801
11     3,5  5.929242          0.672969                  0.703419
6      6,3  5.377346          0.614445                  0.702569
9     11,6  5.043993          0.619689                  0.700273
16     9,5  5.142467          0.609685                  0.700259
10     8,5  5.468417          0.606469                  0.696026
35     7,7  5.227271          0.580265                  0.694572
33    10,6  5.137433          0.598422                  0.692973
12     9,6  5.122434          0.594869                   0.69236
48     5,3  5.165557          0.617423                  0.691786
3      4,4  5.232075          0.596039                  0.690349
28     8,6  5.292727          0.582591                  0.689577
29     8,8  5.147642          0.581540                   0.68595
8      6,4  5.239246          0.587434                  0.684967
20     7,6  5.210208          0.569754                  0.683641
39     7,4  5.138246          0.588485                   0.68214
50     9,9  5.014640          0.585669                  0.679457
0      5,5  5.303888          0.588587                  0.678426
14     5,4  5.338598          0.596991                  0.676921
25     6,5  5.241968          0.576165                  0.675577
1     10,8  4.877746          0.579744                  0.675435
27     7,5  5.053708          0.564212                  0.674674
5      4,5  5.629769          0.623215                  0.674619
22     8,4  5.275103          0.604394                  0.673615
23     5,6  5.182341          0.594698                  0.673137
18     9,7  4.744064          0.576182                  0.672389
7      8,7  5.061327          0.567486                  0.670923
15     9,8  5.036826          0.568222                  0.670643
2      6,6  5.165543          0.572526                  0.670329
40     4,6  5.389964          0.637154                  0.668466

[165 rows x 4 columns]

In [29]:
places.loc[places['place']=='3,2']

   place   Entropy  SpatialDiversity SpatialDiversity-Incoming
42   3,2  5.245417           0.65074                  0.752559

In [29]:
places.to_csv('data/places_entropy2.csv', index=False)

In [26]:
c = SpatialDiversity(data, '10,10')
c

0.88068685340651942