In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('data/manhattan_jan_time.csv')

In [3]:
data

,pickup_datetime,pickup_latitude,pickup_longitude,trip_distance,passenger_count,dropoff_datetime,dropoff_latitude,dropoff_longitude,fare_amount,tolls_amount,...,pickup_neighborhood,dropoff_neighborhood,pickups_place,dropoff_place,dummy,pick_day,pick_weekday,time,pick_hour,weekgroup
0,2016-01-01 00:00:00,40.73470,-73.99037,1.10,2,2016-01-01 00:00:00,40.73241,-73.98184,7.5,0.0,...,Greenwich Village,Gramercy,"5,5","5,6",1,1,4,2016-01-01 00:00:00,0,1
1,2016-01-01 00:00:00,40.78133,-73.96062,1.76,3,2016-01-01 00:00:00,40.75851,-73.97726,8.0,0.0,...,Upper East Side,Midtown,"10,8","7,6",1,1,4,2016-01-01 00:00:00,0,1
2,2016-01-01 00:00:00,40.74305,-73.98012,5.52,2,2016-01-01 00:18:30,40.76314,-73.91349,19.0,0.0,...,Gramercy,Astoria-Long Island City,"6,6","8,12",1,1,4,2016-01-01 00:00:00,0,1
3,2016-01-01 00:00:00,40.71999,-73.99406,7.45,2,2016-01-01 00:26:45,40.78987,-73.96636,26.0,0.0,...,Lower East Side,Upper West Side,"4,4","11,7",1,1,4,2016-01-01 00:00:00,0,1
4,2016-01-01 00:00:01,40.74461,-73.97942,1.20,1,2016-01-01 00:11:55,40.75394,-73.99203,9.0,0.0,...,Gramercy,Garment District,"6,6","7,5",1,1,4,2016-01-01 00:00:01,0,1
5,2016-01-01 00:00:02,40.79105,-73.94715,6.00,1,2016-01-01 00:11:14,40.86558,-73.92077,18.0,0.0,...,Yorkville,Inwood,"11,9","18,11",1,1,4,2016-01-01 00:00:02,0,1
6,2016-01-01 00:00:03,40.72154,-73.98902,0.01,4,2016-01-01 00:00:11,40.72170,-73.98896,2.5,0.0,...,Lower East Side,Lower East Side,"4,5","4,5",1,1,4,2016-01-01 00:00:03,0,1
7,2016-01-01 00:00:03,40.74492,-74.00615,0.79,1,2016-01-01 00:06:19,40.74144,-73.99380,6.0,0.0,...,Chelsea,Chelsea,"6,3","6,5",1,1,4,2016-01-01 00:00:03,0,1
8,2016-01-01 00:00:03,40.76354,-73.96933,2.43,6,2016-01-01 00:15:49,40.74425,-73.99569,12.0,0.0,...,Upper East Side,Chelsea,"8,7","6,4",1,1,4,2016-01-01 00:00:03,0,1
9,2016-01-01 00:00:04,40.74224,-74.00430,3.70,1,2016-01-01 00:14:32,40.70694,-74.00736,14.0,0.0,...,Chelsea,Financial District,"6,4","2,3",1,1,4,2016-01-01 00:00:04,0,1
10,2016-01-01 00:00:05,40.79536,-73.97309,1.92,1,2016-01-01 00:07:14,40.77315,-73.97837,7.5,0.0,...,Upper West Side,Upper West Side,"11,6","9,6",1,1,4,2016-01-01 00:00:05,0,1
11,2016-01-01 00:00:05,40.76895,-73.98516,0.54,1,2016-01-01 00:07:17,40.76173,-73.99023,6.0,0.0,...,Midtown,Clinton,"8,5","8,5",1,1,4,2016-01-01 00:00:05,0,1
12,2016-01-01 00:00:05,40.71858,-73.99200,2.20,2,2016-01-01 00:14:27,40.73994,-74.00513,11.0,0.0,...,Lower East Side,West Village,"3,5","6,3",1,1,4,2016-01-01 00:00:05,0,1
13,2016-01-01 00:00:06,40.77470,-73.98210,1.70,1,2016-01-01 00:04:44,40.79671,-73.97094,7.0,0.0,...,Upper West Side,Upper West Side,"9,6","11,7",1,1,4,2016-01-01 00:00:06,0,1
14,2016-01-01 00:00:06,40.71850,-73.99484,1.38,1,2016-01-01 00:07:14,40.73423,-73.98981,7.0,0.0,...,Lower East Side,Greenwich Village,"3,4","5,5",1,1,4,2016-01-01 00:00:06,0,1
15,2016-01-01 00:00:07,40.72659,-73.98917,1.80,1,2016-01-01 00:09:49,40.71507,-74.00948,9.0,0.0,...,East Village,Tribeca,"4,5","3,3",1,1,4,2016-01-01 00:00:07,0,1
16,2016-01-01 00:00:08,40.73668,-73.99741,0.69,1,2016-01-01 00:03:24,40.73268,-73.98566,4.5,0.0,...,Greenwich Village,East Village,"5,4","5,5",1,1,4,2016-01-01 00:00:08,0,1
17,2016-01-01 00:00:08,40.74722,-73.99714,0.72,1,2016-01-01 00:04:37,40.75180,-74.00449,5.0,0.0,...,Chelsea,Chelsea,"6,4","7,4",1,1,4,2016-01-01 00:00:08,0,1
18,2016-01-01 00:00:08,40.72017,-73.99907,3.09,1,2016-01-01 00:18:51,40.75656,-73.97339,14.5,0.0,...,Little Italy,Midtown,"4,4","7,6",1,1,4,2016-01-01 00:00:08,0,1
19,2016-01-01 00:00:09,40.73696,-73.99713,5.30,3,2016-01-01 00:19:03,40.75558,-73.92842,18.0,0.0,...,Greenwich Village,Astoria-Long Island City,"5,4","7,11",1,1,4,2016-01-01 00:00:09,0,1
20,2016-01-01 00:00:10,40.77807,-73.95441,0.87,1,2016-01-01 00:02:20,40.78858,-73.94893,4.5,0.0,...,Upper East Side,Yorkville,"9,8","10,9",1,1,4,2016-01-01 00:00:10,0,1
21,2016-01-01 00:00:10,40.74390,-73.99940,0.97,2,2016-01-01 00:06:15,40.74532,-73.98888,6.0,0.0,...,Chelsea,Chelsea,"6,4","6,5",1,1,4,2016-01-01 00:00:10,0,1
22,2016-01-01 00:00:14,40.77201,-73.99027,0.44,2,2016-01-01 00:02:38,40.76977,-73.99504,4.0,0.0,...,Upper West Side,Midtown,"9,5","9,4",1,1,4,2016-01-01 00:00:14,0,1
23,2016-01-01 00:00:14,40.74424,-73.99560,2.40,1,2016-01-01 00:13:02,40.76871,-73.98546,11.0,0.0,...,Chelsea,Midtown,"6,4","8,5",1,1,4,2016-01-01 00:00:14,0,1
24,2016-01-01 00:00:16,40.77488,-73.98215,2.90,2,2016-01-01 00:33:00,40.74411,-73.98136,20.5,0.0,...,Upper West Side,Gramercy,"9,6","6,6",1,1,4,2016-01-01 00:00:16,0,1
25,2016-01-01 00:00:17,40.73064,-74.00268,1.50,1,2016-01-01 00:13:59,40.72621,-73.98042,10.0,0.0,...,Greenwich Village,East Village,"5,4","4,6",1,1,4,2016-01-01 00:00:17,0,1
26,2016-01-01 00:00:17,40.71916,-73.98174,9.63,5,2016-01-01 00:14:26,40.82918,-73.93883,27.0,0.0,...,Lower East Side,Harlem,"3,6","15,10",1,1,4,2016-01-01 00:00:17,0,1
27,2016-01-01 00:00:17,40.74207,-74.00806,1.20,1,2016-01-01 00:19:14,40.74216,-74.00229,12.5,0.0,...,West Village,Chelsea,"6,3","6,4",1,1,4,2016-01-01 00:00:17,0,1
28,2016-01-01 00:00:17,40.77374,-73.98166,2.32,1,2016-01-01 00:42:23,40.75384,-73.99596,19.0,0.0,...,Upper West Side,Clinton,"9,6","7,4",1,1,4,2016-01-01 00:00:17,0,1
29,2016-01-01 00:00:18,40.77502,-73.96306,1.17,5,2016-01-01 00:05:44,40.77880,-73.95174,6.0,0.0,...,Upper East Side,Upper East Side,"9,7","9,8",1,1,4,2016-01-01 00:00:18,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9423006,2016-01-31 23:59:36,40.75265,-73.97336,0.87,2,2016-02-01 00:02:22,40.76377,-73.96489,5.0,0.0,...,Midtown,Upper East Side,"7,6","8,7",1,31,6,2016-01-31 23:59:36,23,3
9423007,2016-01-31 23:59:36,40.72885,-73.97673,4.61,1,2016-02-01 00:17:26,40.67954,-73.97581,16.5,0.0,...,East Village,Park Slope,"4,6","0,6",1,31,6,2016-01-31 23:59:36,23,3
9423008,2016-01-31 23:59:36,40.73092,-74.00096,5.20,2,2016-02-01 00:19:20,40.67475,-73.96318,18.5,0.0,...,Greenwich Village,Fort Green,"5,4","0,7",1,31,6,2016-01-31 23:59:36,23,3
9423009,2016-01-31 23:59:37,40.74380,-74.00616,1.60,1,2016-02-01 00:07:11,40.74304,-73.98853,7.5,0.0,...,Chelsea,Gramercy,"6,3","6,5",1,31,6,2016-01-31 23:59:37,23,3
9423010,2016-01-31 23:59:38,40.77369,-73.95777,2.42,5,2016-02-01 00:06:58,40.79863,-73.93351,9.0,0.0,...,Upper East Side,East Harlem,"9,8","11,10",1,31,6,2016-01-31 23:59:38,23,3
9423011,2016-01-31 23:59:39,40.72703,-73.98561,2.57,1,2016-02-01 00:18:24,40.77376,-73.93034,15.0,0.0,...,East Village,Astoria-Long Island City,"4,5","9,10",1,31,6,2016-01-31 23:59:39,23,3
9423012,2016-01-31 23:59:40,40.79461,-73.97149,9.60,1,2016-02-01 00:34:03,40.83978,-73.91837,34.0,0.0,...,Upper West Side,High Bridge,"11,7","16,12",1,31,6,2016-01-31 23:59:40,23,3
9423013,2016-01-31 23:59:41,40.80455,-73.93737,0.05,1,2016-02-01 00:03:56,40.80431,-73.93758,4.5,0.0,...,Harlem,East Harlem,"12,10","12,10",1,31,6,2016-01-31 23:59:41,23,3
9423014,2016-01-31 23:59:41,40.75937,-73.98458,5.65,2,2016-02-01 00:16:32,40.82013,-73.95499,19.5,0.0,...,Midtown,Hamilton Heights,"7,5","14,8",1,31,6,2016-01-31 23:59:41,23,3
9423015,2016-01-31 23:59:44,40.73288,-74.00397,6.74,1,2016-02-01 00:22:53,40.67239,-73.93101,23.0,0.0,...,West Village,Bedford-Stuyvesant,"5,4","0,10",1,31,6,2016-01-31 23:59:44,23,3
9423016,2016-01-31 23:59:45,40.71875,-73.98812,4.15,3,2016-02-01 00:15:23,40.70059,-73.92170,15.0,0.0,...,Lower East Side,Bushwick,"3,5","2,11",1,31,6,2016-01-31 23:59:45,23,3
9423017,2016-01-31 23:59:46,40.72048,-73.98719,1.30,1,2016-02-01 00:07:46,40.73141,-73.97496,7.5,0.0,...,Lower East Side,Gramercy,"4,5","5,6",1,31,6,2016-01-31 23:59:46,23,3
9423018,2016-01-31 23:59:48,40.72889,-73.98440,0.70,2,2016-02-01 00:04:44,40.73559,-73.99236,5.5,0.0,...,East Village,Greenwich Village,"4,5","5,5",1,31,6,2016-01-31 23:59:48,23,3
9423019,2016-01-31 23:59:49,40.72438,-73.98756,6.55,1,2016-02-01 00:22:36,40.80084,-73.95860,21.5,0.0,...,East Village,Harlem,"4,5","12,8",1,31,6,2016-01-31 23:59:49,23,3
9423020,2016-01-31 23:59:51,40.74284,-73.98109,0.71,1,2016-02-01 00:03:15,40.75063,-73.97881,4.5,0.0,...,Gramercy,Murray Hill,"6,6","7,6",1,31,6,2016-01-31 23:59:51,23,3
9423021,2016-01-31 23:59:52,40.73639,-73.98493,0.99,1,2016-02-01 00:03:20,40.74887,-73.97607,5.0,0.0,...,Gramercy,Murray Hill,"5,5","6,6",1,31,6,2016-01-31 23:59:52,23,3
9423022,2016-01-31 23:59:52,40.76479,-73.97318,1.00,1,2016-02-01 00:03:43,40.76172,-73.98613,5.5,0.0,...,Central Park,Midtown,"8,6","8,5",1,31,6,2016-01-31 23:59:52,23,3
9423023,2016-01-31 23:59:52,40.75505,-73.97508,1.14,1,2016-02-01 00:03:46,40.74207,-73.98282,5.5,0.0,...,Midtown,Gramercy,"7,6","6,6",1,31,6,2016-01-31 23:59:52,23,3
9423024,2016-01-31 23:59:53,40.72983,-74.00057,2.10,1,2016-02-01 00:11:03,40.72578,-73.98377,10.0,0.0,...,Greenwich Village,East Village,"5,4","4,5",1,31,6,2016-01-31 23:59:53,23,3
9423025,2016-01-31 23:59:53,40.71606,-74.00703,5.44,6,2016-02-01 00:18:18,40.78402,-73.97618,18.5,0.0,...,Tribeca,Upper West Side,"3,3","10,6",1,31,6,2016-01-31 23:59:53,23,3
9423026,2016-01-31 23:59:56,40.74187,-73.99355,2.49,1,2016-02-01 00:06:28,40.76187,-73.96685,9.0,0.0,...,Chelsea,Upper East Side,"6,5","8,7",1,31,6,2016-01-31 23:59:56,23,3
9423027,2016-01-31 23:59:56,40.72383,-74.00466,2.40,1,2016-02-01 00:08:03,40.74717,-73.98119,9.5,0.0,...,Soho,Gramercy,"4,3","6,6",1,31,6,2016-01-31 23:59:56,23,3
9423028,2016-01-31 23:59:57,40.74152,-73.98744,2.74,1,2016-02-01 00:09:00,40.71005,-74.00619,10.5,0.0,...,Gramercy,Financial District,"6,5","3,3",1,31,6,2016-01-31 23:59:57,23,3
9423029,2016-01-31 23:59:57,40.72486,-73.99236,3.40,1,2016-02-01 00:13:28,40.76514,-73.97666,13.5,0.0,...,East Village,Midtown,"4,5","8,6",1,31,6,2016-01-31 23:59:57,23,3
9423030,2016-01-31 23:59:57,40.76300,-73.98600,9.18,2,2016-02-01 00:17:58,40.85940,-73.92785,27.0,0.0,...,Midtown,Washington Heights,"8,5","18,11",1,31,6,2016-01-31 23:59:57,23,3
9423031,2016-01-31 23:59:58,40.75417,-73.98474,2.20,1,2016-02-01 00:07:36,40.78054,-73.98373,9.0,0.0,...,Garment District,Upper West Side,"7,5","10,5",1,31,6,2016-01-31 23:59:58,23,3
9423032,2016-01-31 23:59:59,40.73433,-74.00294,0.80,2,2016-02-01 00:07:26,40.73919,-73.99695,6.5,0.0,...,West Village,Chelsea,"5,4","5,4",1,31,6,2016-01-31 23:59:59,23,3
9423033,2016-01-31 23:59:59,40.72823,-73.99911,1.10,1,2016-02-01 00:09:28,40.73845,-73.99717,8.0,0.0,...,Greenwich Village,Chelsea,"4,4","5,4",1,31,6,2016-01-31 23:59:59,23,3
9423034,2016-01-31 23:59:59,40.72007,-73.98833,2.64,1,2016-02-01 00:12:16,40.74385,-74.00665,11.0,0.0,...,Lower East Side,Chelsea,"4,5","6,3",1,31,6,2016-01-31 23:59:59,23,3
9423035,2016-01-31 23:59:59,40.72289,-73.98891,3.95,1,2016-02-01 00:13:01,40.68917,-73.96004,14.0,0.0,...,Lower East Side,Fort Green,"4,5","0,8",1,31,6,2016-01-31 23:59:59,23,3

In [6]:
grid4_5 = data.loc[ (data['pickups_place']=='4,5') ,:]
grid4_5['dropoff_place'].value_counts()

5,5        24590
4,5        21091
6,6        20469
6,5        18727
5,4        18392
4,4        18306
5,6        14006
7,6        11753
4,6        11456
7,5        11020
6,4        10468
7,7         8940
2,3         8671
3,5         8241
3,3         7899
3,4         6778
5,3         6321
8,6         5843
9,8         5535
8,5         5431
8,8         5294
7,4         4362
4,3         4249
8,7         4237
6,3         4222
9,9         2971
10,9        2435
0,6         2391
3,6         2332
9,6         2256
           ...
-3,1           1
-12,-12        1
21,20          1
-4,-5          1
14,20          1
-8,11          1
-6,-8          1
-7,-5          1
-7,-7          1
-7,-6          1
-7,-9          1
-7,-8          1
14,19          1
5,30           1
-9,23          1
3,11           1
-4,5           1
18,19          1
-8,13          1
-6,13          1
12,23          1
7,30           1
-3,14          1
6,31           1
4,10           1
21,15          1
-11,-7         1
-11,-5         1
-11,-4         1
5,25           1
Name: dropoff_place, Length: 524, dtype: int64

In [24]:
grid4_5_2 = data.loc[ (data['pickups_place']=='4,5')&( data['weekgroup']==2 )&(data['pick_hour']==1) ,['dropoff_place','dummy']]
grid4_5_2['dropoff_place'].value_counts()

6,6      706
4,5      660
5,5      523
5,4      441
4,4      411
5,6      409
4,6      323
6,5      311
7,7      272
6,4      256
2,3      238
3,5      235
9,8      186
7,5      185
8,5      181
3,3      176
7,6      168
8,8      153
5,3      143
3,4      117
7,4      108
8,6      105
10,9      97
9,9       94
6,3       86
10,6      79
8,7       78
9,6       72
0,8       70
0,6       67
        ...
21,16      1
17,19      1
7,9        1
-8,-1      1
17,11      1
17,13      1
19,13      1
-9,22      1
2,24       1
-6,9       1
7,24       1
-7,5       1
-6,0       1
-6,3       1
-6,2       1
-6,4       1
17,17      1
1,17       1
13,21      1
7,29       1
20,14      1
12,18      1
12,11      1
14,15      1
14,10      1
21,12      1
9,23       1
-9,-6      1
2,6        1
16,14      1
Name: dropoff_place, Length: 233, dtype: int64

In [27]:
dropoffs_4_5 = grid4_5_2['dropoff_place'].unique()
dropoffs_4_5 = None

In [64]:
totalrides_4_5 = grid4_5['dummy'].sum()
totalrides_4_5

338909

In [75]:
entropy_4_5 = pd.DataFrame(grid4_5['dropoff_place'].value_counts())
entropy_4_5['freq']  =entropy_4_5['dropoff_place']
entropy_4_5.drop('dropoff_place', axis=1, inplace=True)
entropy_4_5

          freq
5,5      24590
4,5      21091
6,6      20469
6,5      18727
5,4      18392
4,4      18306
5,6      14006
7,6      11753
4,6      11456
7,5      11020
6,4      10468
7,7       8940
2,3       8671
3,5       8241
3,3       7899
3,4       6778
5,3       6321
8,6       5843
9,8       5535
8,5       5431
8,8       5294
7,4       4362
4,3       4249
8,7       4237
6,3       4222
9,9       2971
10,9      2435
0,6       2391
3,6       2332
9,6       2256
...        ...
-3,1         1
-12,-12      1
21,20        1
-4,-5        1
14,20        1
-8,11        1
-6,-8        1
-7,-5        1
-7,-7        1
-7,-6        1
-7,-9        1
-7,-8        1
14,19        1
5,30         1
-9,23        1
3,11         1
-4,5         1
18,19        1
-8,13        1
-6,13        1
12,23        1
7,30         1
-3,14        1
6,31         1
4,10         1
21,15        1
-11,-7       1
-11,-5       1
-11,-4       1
5,25         1

[524 rows x 1 columns]

In [76]:
entropy_4_5['prob'] = entropy_4_5['freq']/totalrides_4_5

entropy_4_5.head(5)

      freq      prob
5,5  24590  0.072556
4,5  21091  0.062232
6,6  20469  0.060397
6,5  18727  0.055257
5,4  18392  0.054268

In [81]:
import math
entropy_4_5['log_prob'] = entropy_4_5['prob'].apply(lambda x:math.log(x,2))
entropy_4_5['product'] = entropy_4_5['prob']*entropy_4_5['log_prob']
entropy_4_5.head(15)

      freq      prob  log_prob   product
5,5  24590  0.072556 -3.784754 -0.274608
4,5  21091  0.062232 -4.006199 -0.249314
6,6  20469  0.060397 -4.049385 -0.244570
6,5  18727  0.055257 -4.177706 -0.230846
5,4  18392  0.054268 -4.203748 -0.228130
4,4  18306  0.054014 -4.210509 -0.227429
5,6  14006  0.041327 -4.596781 -0.189970
7,6  11753  0.034679 -4.849797 -0.168186
4,6  11456  0.033803 -4.886723 -0.165184
7,5  11020  0.032516 -4.942702 -0.160717
6,4  10468  0.030887 -5.016840 -0.154957
7,7   8940  0.026379 -5.244479 -0.138343
2,3   8671  0.025585 -5.288556 -0.135308
3,5   8241  0.024316 -5.361935 -0.130382
3,3   7899  0.023307 -5.423084 -0.126397

In [83]:
Entropy4_5 = -1*entropy_4_5['product'].sum()
Entropy4_5

5.6297690639359574

AHORA A HACER LO MISMO PERO CON EL CUADRANTE 3,5

In [70]:
grid3_5 = data.loc[ (data['pickups_place']=='3,5') ,:]
totalrides_3_5 = grid3_5['dummy'].sum()
totalrides_3_5

84033

In [71]:
grid3_5

,pickup_datetime,pickup_latitude,pickup_longitude,trip_distance,passenger_count,dropoff_datetime,dropoff_latitude,dropoff_longitude,fare_amount,tolls_amount,...,pickup_neighborhood,dropoff_neighborhood,pickups_place,dropoff_place,dummy,pick_day,pick_weekday,time,pick_hour,weekgroup
12,2016-01-01 00:00:05,40.71858,-73.99200,2.20,2,2016-01-01 00:14:27,40.73994,-74.00513,11.0,0.0,...,Lower East Side,West Village,"3,5","6,3",1,1,4,2016-01-01 00:00:05,0,1
148,2016-01-01 00:01:43,40.71822,-73.98663,1.34,1,2016-01-01 00:12:33,40.72938,-73.99989,8.5,0.0,...,Lower East Side,Greenwich Village,"3,5","4,4",1,1,4,2016-01-01 00:01:43,0,1
192,2016-01-01 00:02:13,40.71478,-73.99022,5.60,1,2016-01-01 00:28:18,40.77731,-73.97871,21.0,0.0,...,Lower East Side,Upper West Side,"3,5","9,6",1,1,4,2016-01-01 00:02:13,0,1
307,2016-01-01 00:03:12,40.71909,-73.98972,5.40,2,2016-01-01 00:21:03,40.76408,-73.97717,19.5,0.0,...,Lower East Side,Midtown,"3,5","8,6",1,1,4,2016-01-01 00:03:12,0,1
343,2016-01-01 00:03:27,40.71638,-73.98927,3.90,1,2016-01-01 00:14:15,40.75215,-73.96957,13.5,0.0,...,Lower East Side,Midtown,"3,5","7,7",1,1,4,2016-01-01 00:03:27,0,1
394,2016-01-01 00:03:49,40.71936,-73.98486,4.00,1,2016-01-01 00:22:03,40.68800,-73.96725,16.5,0.0,...,Lower East Side,Fort Green,"3,5","0,7",1,1,4,2016-01-01 00:03:49,0,1
425,2016-01-01 00:04:03,40.71930,-73.99036,3.88,1,2016-01-01 00:22:47,40.75981,-73.99535,15.5,0.0,...,Lower East Side,Clinton,"3,5","8,4",1,1,4,2016-01-01 00:04:03,0,1
482,2016-01-01 00:04:23,40.71944,-73.99060,4.39,5,2016-01-01 00:30:46,40.76403,-73.99058,20.0,0.0,...,Lower East Side,Clinton,"3,5","8,5",1,1,4,2016-01-01 00:04:23,0,1
551,2016-01-01 00:04:47,40.71959,-73.98666,2.77,1,2016-01-01 00:15:34,40.69243,-73.98702,11.0,0.0,...,Lower East Side,Downtown,"3,5","1,5",1,1,4,2016-01-01 00:04:47,0,1
574,2016-01-01 00:04:56,40.71872,-73.99078,0.64,2,2016-01-01 00:08:49,40.71343,-73.98988,5.0,0.0,...,Lower East Side,Lower East Side,"3,5","3,5",1,1,4,2016-01-01 00:04:56,0,1
589,2016-01-01 00:04:58,40.71053,-73.98467,8.79,5,2016-01-01 00:29:53,40.64935,-74.02034,29.0,0.0,...,Lower East Side,Sunset Park,"3,5","-3,2",1,1,4,2016-01-01 00:04:58,0,1
608,2016-01-01 00:05:04,40.71909,-73.98965,2.20,1,2016-01-01 00:12:45,40.69506,-73.98312,9.5,0.0,...,Lower East Side,Fort Green,"3,5","1,6",1,1,4,2016-01-01 00:05:04,0,1
633,2016-01-01 00:05:12,40.71878,-73.98890,2.70,1,2016-01-01 00:11:31,40.74345,-73.97251,9.5,0.0,...,Lower East Side,Gramercy,"3,5","6,7",1,1,4,2016-01-01 00:05:12,0,1
669,2016-01-01 00:05:20,40.71748,-73.98464,0.01,1,2016-01-01 00:05:25,40.71825,-73.98694,2.5,0.0,...,Lower East Side,Lower East Side,"3,5","3,5",1,1,4,2016-01-01 00:05:20,0,1
679,2016-01-01 00:05:24,40.71873,-73.98807,7.49,1,2016-01-01 00:22:10,40.79905,-73.92993,22.5,0.0,...,Lower East Side,East Harlem,"3,5","12,11",1,1,4,2016-01-01 00:05:24,0,1
742,2016-01-01 00:05:46,40.71070,-73.98484,6.40,1,2016-01-01 00:24:45,40.78620,-73.94860,23.0,0.0,...,Lower East Side,Yorkville,"3,5","10,9",1,1,4,2016-01-01 00:05:46,0,1
750,2016-01-01 00:05:48,40.71808,-73.98614,6.19,1,2016-01-01 00:41:05,40.77381,-73.98857,25.5,0.0,...,Lower East Side,Upper West Side,"3,5","9,5",1,1,4,2016-01-01 00:05:48,0,1
787,2016-01-01 00:05:57,40.71879,-73.98934,5.80,1,2016-01-01 00:21:07,40.77637,-73.95016,18.5,0.0,...,Lower East Side,Upper East Side,"3,5","9,9",1,1,4,2016-01-01 00:05:57,0,1
843,2016-01-01 00:06:13,40.71976,-73.99303,1.10,3,2016-01-01 00:15:17,40.73111,-73.98625,7.5,0.0,...,Lower East Side,East Village,"3,5","5,5",1,1,4,2016-01-01 00:06:13,0,1
901,2016-01-01 00:06:31,40.71648,-73.99203,3.70,1,2016-01-01 00:19:31,40.67395,-73.97153,14.0,0.0,...,Lower East Side,Park Slope,"3,5","0,7",1,1,4,2016-01-01 00:06:31,0,1
1052,2016-01-01 00:07:05,40.71530,-73.98441,0.40,2,2016-01-01 00:09:45,40.71342,-73.98161,4.0,0.0,...,Lower East Side,Lower East Side,"3,5","3,6",1,1,4,2016-01-01 00:07:05,0,1
1096,2016-01-01 00:07:15,40.71938,-73.99074,0.90,1,2016-01-01 00:11:29,40.73097,-73.98267,5.0,0.0,...,Lower East Side,East Village,"3,5","5,6",1,1,4,2016-01-01 00:07:15,0,1
1166,2016-01-01 00:07:29,40.71909,-73.98965,1.39,1,2016-01-01 00:16:03,40.73572,-73.98340,7.5,0.0,...,Lower East Side,Gramercy,"3,5","5,5",1,1,4,2016-01-01 00:07:29,0,1
1179,2016-01-01 00:07:31,40.71862,-73.98870,4.93,5,2016-01-01 00:20:21,40.70066,-73.92168,16.0,0.0,...,Lower East Side,Bushwick,"3,5","2,11",1,1,4,2016-01-01 00:07:31,0,1
1195,2016-01-01 00:07:37,40.71686,-73.98906,0.32,1,2016-01-01 00:10:34,40.71726,-73.98519,4.0,0.0,...,Lower East Side,Lower East Side,"3,5","3,5",1,1,4,2016-01-01 00:07:37,0,1
1331,2016-01-01 00:08:07,40.71880,-73.98891,4.60,1,2016-01-01 00:22:59,40.77719,-73.95002,15.0,0.0,...,Lower East Side,Upper East Side,"3,5","9,9",1,1,4,2016-01-01 00:08:07,0,1
1348,2016-01-01 00:08:10,40.71989,-73.98750,7.40,2,2016-01-01 00:26:58,40.79655,-73.96244,23.5,0.0,...,Lower East Side,Upper West Side,"3,5","11,7",1,1,4,2016-01-01 00:08:10,0,1
1510,2016-01-01 00:08:43,40.71895,-73.98907,1.30,1,2016-01-01 00:17:07,40.73076,-74.00331,8.0,0.0,...,Lower East Side,Greenwich Village,"3,5","5,4",1,1,4,2016-01-01 00:08:43,0,1
1543,2016-01-01 00:08:49,40.71889,-73.98980,6.40,2,2016-01-01 00:23:21,40.78527,-73.94953,20.0,0.0,...,Lower East Side,Upper East Side,"3,5","10,9",1,1,4,2016-01-01 00:08:49,0,1
1587,2016-01-01 00:08:59,40.71415,-73.98965,0.61,1,2016-01-01 00:13:09,40.72205,-73.98640,5.0,0.0,...,Lower East Side,Lower East Side,"3,5","4,5",1,1,4,2016-01-01 00:08:59,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421230,2016-01-31 23:41:57,40.71429,-73.99254,3.60,1,2016-01-31 23:58:10,40.68112,-73.95967,14.5,0.0,...,Lower East Side,Fort Green,"3,5","0,8",1,31,6,2016-01-31 23:41:57,23,3
9421301,2016-01-31 23:42:37,40.71895,-73.98904,1.40,2,2016-01-31 23:48:27,40.73446,-73.98951,6.5,0.0,...,Lower East Side,Greenwich Village,"3,5","5,5",1,31,6,2016-01-31 23:42:37,23,3
9421462,2016-01-31 23:43:58,40.71889,-73.98809,4.98,1,2016-02-01 00:01:41,40.67662,-73.94571,17.5,0.0,...,Lower East Side,Bedford-Stuyvesant,"3,5","0,9",1,31,6,2016-01-31 23:43:58,23,3
9421531,2016-01-31 23:44:36,40.71841,-73.98811,0.80,1,2016-01-31 23:50:15,40.72479,-73.98743,5.5,0.0,...,Lower East Side,East Village,"3,5","4,5",1,31,6,2016-01-31 23:44:36,23,3
9421569,2016-01-31 23:44:53,40.71926,-73.98780,2.73,5,2016-01-31 23:58:40,40.75108,-73.97474,12.0,0.0,...,Lower East Side,Murray Hill,"3,5","7,6",1,31,6,2016-01-31 23:44:53,23,3
9421596,2016-01-31 23:45:10,40.71882,-73.98943,3.98,2,2016-01-31 23:59:54,40.70290,-73.92548,14.5,0.0,...,Lower East Side,Bushwick,"3,5","2,11",1,31,6,2016-01-31 23:45:10,23,3
9421627,2016-01-31 23:45:28,40.71748,-73.98589,2.10,1,2016-01-31 23:50:34,40.71289,-73.96761,8.0,0.0,...,Lower East Side,Williamsburg,"3,5","3,7",1,31,6,2016-01-31 23:45:28,23,3
9421635,2016-01-31 23:45:34,40.71979,-73.98752,8.61,1,2016-02-01 00:00:30,40.81005,-73.93723,24.5,0.0,...,Lower East Side,Harlem,"3,5","13,10",1,31,6,2016-01-31 23:45:34,23,3
9421674,2016-01-31 23:45:59,40.71952,-73.98946,2.80,1,2016-01-31 23:56:04,40.71410,-73.94966,11.0,0.0,...,Lower East Side,Williamsburg,"3,5","3,9",1,31,6,2016-01-31 23:45:59,23,3
9421683,2016-01-31 23:46:04,40.71410,-73.99009,3.60,2,2016-01-31 23:57:46,40.68449,-73.96813,12.5,0.0,...,Lower East Side,Fort Green,"3,5","0,7",1,31,6,2016-01-31 23:46:04,23,3
9421691,2016-01-31 23:46:07,40.71886,-73.98883,3.70,1,2016-01-31 23:59:41,40.69283,-73.93114,13.5,0.0,...,Lower East Side,Bedford-Stuyvesant,"3,5","1,10",1,31,6,2016-01-31 23:46:07,23,3
9421863,2016-01-31 23:47:44,40.71940,-73.99121,3.82,1,2016-02-01 00:06:05,40.75659,-73.98847,15.0,0.0,...,Lower East Side,Garment District,"3,5","7,5",1,31,6,2016-01-31 23:47:44,23,3
9421891,2016-01-31 23:48:06,40.71857,-73.99052,7.57,5,2016-02-01 00:04:51,40.80796,-73.92368,23.0,0.0,...,Lower East Side,Mott Haven,"3,5","12,11",1,31,6,2016-01-31 23:48:06,23,3
9421908,2016-01-31 23:48:12,40.71801,-73.98565,0.70,1,2016-01-31 23:53:51,40.72128,-73.99441,5.5,0.0,...,Lower East Side,Little Italy,"3,5","4,4",1,31,6,2016-01-31 23:48:12,23,3
9422154,2016-01-31 23:50:24,40.71924,-73.98780,1.98,2,2016-01-31 23:57:25,40.70888,-73.95612,8.5,0.0,...,Lower East Side,Williamsburg,"3,5","2,8",1,31,6,2016-01-31 23:50:24,23,3
9422172,2016-01-31 23:50:33,40.71957,-73.99107,3.60,1,2016-02-01 00:07:37,40.76026,-73.98764,15.0,0.0,...,Lower East Side,Midtown,"3,5","8,5",1,31,6,2016-01-31 23:50:33,23,3
9422222,2016-01-31 23:51:12,40.71931,-73.99010,1.80,1,2016-01-31 23:59:42,40.73530,-73.99832,8.0,0.0,...,Lower East Side,Greenwich Village,"3,5","5,4",1,31,6,2016-01-31 23:51:12,23,3
9422318,2016-01-31 23:52:13,40.71857,-73.98776,1.20,1,2016-01-31 23:59:09,40.70888,-73.99864,7.0,0.0,...,Lower East Side,Lower East Side,"3,5","2,4",1,31,6,2016-01-31 23:52:13,23,3
9422328,2016-01-31 23:52:19,40.71315,-73.99239,1.70,1,2016-02-01 00:03:00,40.72432,-74.00299,9.0,0.0,...,Lower East Side,Soho,"3,5","4,4",1,31,6,2016-01-31 23:52:19,23,3
9422335,2016-01-31 23:52:26,40.71829,-73.98766,4.55,3,2016-02-01 00:09:14,40.69977,-73.90900,16.0,0.0,...,Lower East Side,Ridgewood,"3,5","1,12",1,31,6,2016-01-31 23:52:26,23,3
9422350,2016-01-31 23:52:39,40.71869,-73.98795,0.90,1,2016-01-31 23:58:02,40.71033,-73.99637,6.0,0.0,...,Lower East Side,Lower East Side,"3,5","3,4",1,31,6,2016-01-31 23:52:39,23,3
9422549,2016-01-31 23:54:48,40.71563,-73.98975,0.90,2,2016-01-31 23:58:40,40.72003,-73.97896,5.0,0.0,...,Lower East Side,Lower East Side,"3,5","4,6",1,31,6,2016-01-31 23:54:48,23,3
9422583,2016-01-31 23:55:07,40.71957,-73.99004,1.50,1,2016-02-01 00:00:48,40.73863,-73.98221,7.0,0.0,...,Lower East Side,Gramercy,"3,5","5,6",1,31,6,2016-01-31 23:55:07,23,3
9422615,2016-01-31 23:55:27,40.71854,-73.98777,1.43,1,2016-02-01 00:02:13,40.73283,-73.98995,7.0,0.0,...,Lower East Side,Greenwich Village,"3,5","5,5",1,31,6,2016-01-31 23:55:27,23,3
9422671,2016-01-31 23:56:04,40.71843,-73.99377,0.62,2,2016-02-01 00:01:19,40.71353,-73.98955,5.5,0.0,...,Lower East Side,Lower East Side,"3,5","3,5",1,31,6,2016-01-31 23:56:04,23,3
9422909,2016-01-31 23:58:30,40.71392,-73.99273,12.40,1,2016-02-01 00:22:37,40.84607,-73.94250,36.0,0.0,...,Lower East Side,Washington Heights,"3,5","16,9",1,31,6,2016-01-31 23:58:30,23,3
9422984,2016-01-31 23:59:22,40.71530,-73.98993,3.36,1,2016-02-01 00:12:09,40.68271,-73.98247,12.5,0.0,...,Lower East Side,Boerum Hill,"3,5","0,6",1,31,6,2016-01-31 23:59:22,23,3
9423001,2016-01-31 23:59:33,40.71563,-73.99035,6.16,1,2016-02-01 00:11:51,40.73716,-73.89898,18.5,0.0,...,Lower East Side,Maspeth,"3,5","5,13",1,31,6,2016-01-31 23:59:33,23,3
9423005,2016-01-31 23:59:35,40.71747,-73.99118,1.60,1,2016-02-01 00:09:01,40.70950,-74.00613,8.5,0.0,...,Lower East Side,Financial District,"3,5","2,3",1,31,6,2016-01-31 23:59:35,23,3
9423016,2016-01-31 23:59:45,40.71875,-73.98812,4.15,3,2016-02-01 00:15:23,40.70059,-73.92170,15.0,0.0,...,Lower East Side,Bushwick,"3,5","2,11",1,31,6,2016-01-31 23:59:45,23,3

In [72]:
entropy_3_5 = pd.DataFrame(grid3_5['dropoff_place'].value_counts())
#entropy_4_5['prob']=entropy_4_5['freq'] /totalrides_4_5
entropy_3_5['freq']  =entropy_3_5['dropoff_place']
entropy_3_5.drop('dropoff_place', axis=1, inplace=True)
entropy_3_5

         freq
4,5      6668
5,5      4411
4,4      4211
4,6      3744
6,6      3580
2,3      3170
5,6      3105
6,5      2960
5,4      2839
3,5      2540
3,3      2528
3,4      2354
7,5      2089
6,4      1887
7,6      1751
7,7      1570
3,6      1408
5,3      1255
3,8      1245
8,5      1083
9,8      1022
3,7       974
8,8       944
4,3       932
7,4       856
8,6       821
0,6       821
1,10      818
6,3       818
2,9       776
...       ...
4,23        1
4,21        1
4,28        1
-5,12       1
-5,-9       1
-5,-4       1
-5,-6       1
-5,-7       1
22,16       1
22,14       1
22,12       1
16,19       1
16,16       1
-13,-13     1
-3,14       1
-3,12       1
-3,13       1
-3,10       1
23,14       1
19,18       1
7,31        1
7,23        1
-7,26       1
-7,28       1
-10,18      1
-8,3        1
-6,8        1
7,19        1
-10,19      1
1,29        1

[449 rows x 1 columns]

In [85]:
totalrides_3_5 = grid3_5['dummy'].sum()
totalrides_3_5

84033

In [87]:
entropy_3_5['prob'] = entropy_3_5['freq']/totalrides_3_5

entropy_3_5.head(5)

     freq      prob
4,5  6668  0.079350
5,5  4411  0.052491
4,4  4211  0.050111
4,6  3744  0.044554
6,6  3580  0.042602

In [88]:
entropy_3_5['log_prob'] = entropy_3_5['prob'].apply(lambda x:math.log(x,2))
entropy_3_5['product'] = entropy_3_5['prob']*entropy_3_5['log_prob']
entropy_3_5.head(15)

     freq      prob  log_prob   product
4,5  6668  0.079350 -3.655630 -0.290073
5,5  4411  0.052491 -4.251778 -0.223181
4,4  4211  0.050111 -4.318721 -0.216417
4,6  3744  0.044554 -4.488304 -0.199972
6,6  3580  0.042602 -4.552924 -0.193965
2,3  3170  0.037723 -4.728401 -0.178371
5,6  3105  0.036950 -4.758291 -0.175818
6,5  2960  0.035224 -4.827287 -0.170038
5,4  2839  0.033784 -4.887501 -0.165121
3,5  2540  0.030226 -5.048056 -0.152584
3,3  2528  0.030083 -5.054888 -0.152068
3,4  2354  0.028013 -5.157770 -0.144484
7,5  2089  0.024859 -5.330072 -0.132502
6,4  1887  0.022455 -5.476790 -0.122984
7,6  1751  0.020837 -5.584705 -0.116369

In [89]:
Entropy3_5 = -1*entropy_3_5['product'].sum()
Entropy3_5

5.9292416665609382

In [90]:
grid7_6 = data.loc[ (data['pickups_place']=='7,6') ,:]
totalrides_7_6 = grid7_6['dummy'].sum()
totalrides_7_6
entropy_7_6 = pd.DataFrame(grid7_6['dropoff_place'].value_counts())
#entropy_4_5['prob']=entropy_4_5['freq'] /totalrides_4_5
entropy_7_6['freq']  =entropy_7_6['dropoff_place']
entropy_7_6.drop('dropoff_place', axis=1, inplace=True)
entropy_7_6

          freq
7,5      58362
6,5      50777
8,6      44868
8,7      35848
7,6      33730
6,6      33046
7,7      25072
5,5      24297
9,8      22960
8,5      19959
8,8      18531
5,4      13234
6,4      12640
10,8     12483
7,4      12450
4,4      11223
4,5      10927
9,6      10895
5,6      10669
2,3       9453
3,3       9057
9,7       8728
8,4       8468
10,6      8158
9,9       7937
9,5       6222
6,3       5424
10,9      5085
4,3       4622
5,3       4602
...        ...
5,8          1
8,25         1
8,24         1
-17,-18      1
-5,12        1
-14,-11      1
-2,16        1
-7,26        1
-6,-4        1
-2,7         1
-9,-2        1
11,12        1
7,32         1
-2,15        1
7,30         1
-6,-3        1
-10,-11      1
-12,-10      1
0,21         1
19,10        1
-10,17       1
6,19         1
6,23         1
2,27         1
-13,-15      1
2,29         1
-13,-16      1
-6,-5        1
22,19        1
-1,16        1

[566 rows x 1 columns]

In [91]:
entropy_7_6['prob'] = entropy_7_6['freq']/totalrides_7_6
entropy_7_6['log_prob'] = entropy_7_6['prob'].apply(lambda x:math.log(x,2))
entropy_7_6['product'] = entropy_7_6['prob']*entropy_7_6['log_prob']
entropy_7_6.head(15)

       freq      prob  log_prob   product
7,5   58362  0.096737 -3.369791 -0.325983
6,5   50777  0.084164 -3.570645 -0.300521
8,6   44868  0.074370 -3.749134 -0.278823
8,7   35848  0.059419 -4.072928 -0.242010
7,6   33730  0.055909 -4.160788 -0.232623
6,6   33046  0.054775 -4.190345 -0.229525
7,7   25072  0.041558 -4.588743 -0.190697
5,5   24297  0.040273 -4.634042 -0.186627
9,8   22960  0.038057 -4.715698 -0.179465
8,5   19959  0.033083 -4.917781 -0.162693
8,8   18531  0.030716 -5.024880 -0.154343
5,4   13234  0.021936 -5.510571 -0.120879
6,4   12640  0.020951 -5.576824 -0.116841
10,8  12483  0.020691 -5.594856 -0.115763
7,4   12450  0.020636 -5.598675 -0.115536

In [92]:
Entropy7_6 = -1*entropy_7_6['product'].sum()
Entropy7_6

5.2102078695719731

In [93]:
grid4_5_1 = data.loc[ (data['pickups_place']=='4,5')&( data['weekgroup']==2 )&(data['pick_hour']==1) ,['dropoff_place','dummy']]
totalrides_4_5_1 = grid4_5_1['dummy'].sum()
entropy_4_5_1 = pd.DataFrame(grid4_5_1['dropoff_place'].value_counts())
entropy_4_5_1['freq']  =entropy_4_5_1['dropoff_place']
entropy_4_5_1.drop('dropoff_place', axis=1, inplace=True)
entropy_4_5_1['prob'] = entropy_4_5_1['freq']/totalrides_4_5_1
entropy_4_5_1['log_prob'] = entropy_4_5_1['prob'].apply(lambda x:math.log(x,2))
entropy_4_5_1['product'] = entropy_4_5_1['prob']*entropy_4_5_1['log_prob']
entropy_4_5_1.head(15)

     freq      prob  log_prob   product
6,6   706  0.080392 -3.636809 -0.292369
4,5   660  0.075154 -3.734012 -0.280625
5,5   523  0.059554 -4.069667 -0.242363
5,4   441  0.050216 -4.315699 -0.216719
4,4   411  0.046800 -4.417339 -0.206733
5,6   409  0.046573 -4.424377 -0.206054
4,6   323  0.036780 -4.764943 -0.175254
6,5   311  0.035413 -4.819563 -0.170677
7,7   272  0.030972 -5.012871 -0.155261
6,4   256  0.029151 -5.100334 -0.148677
2,3   238  0.027101 -5.205516 -0.141074
3,5   235  0.026759 -5.223817 -0.139786
9,8   186  0.021180 -5.561175 -0.117784
7,5   185  0.021066 -5.568952 -0.117315
8,5   181  0.020610 -5.600488 -0.115428

In [94]:
Entropy4_5_1 = -1*entropy_4_5_1['product'].sum()
Entropy4_5_1

5.7296698211920747

Entropia de lunes a jueves a las 1 de la manana

In [95]:
grid4_5_1week = data.loc[ (data['pickups_place']=='4,5')&( data['weekgroup']==0 )&(data['pick_hour']==1) ,['dropoff_place','dummy']]
totalrides_4_5_1week = grid4_5_1week['dummy'].sum()
entropy_4_5_1week = pd.DataFrame(grid4_5_1week['dropoff_place'].value_counts())
entropy_4_5_1week['freq']  =entropy_4_5_1week['dropoff_place']
entropy_4_5_1week.drop('dropoff_place', axis=1, inplace=True)
entropy_4_5_1week['prob'] = entropy_4_5_1week['freq']/totalrides_4_5_1
entropy_4_5_1week['log_prob'] = entropy_4_5_1week['prob'].apply(lambda x:math.log(x,2))
entropy_4_5_1week['product'] = entropy_4_5_1week['prob']*entropy_4_5_1week['log_prob']
entropy_4_5_1week.head(15)

     freq      prob  log_prob   product
4,5   353  0.040196 -4.636809 -0.186381
5,4   215  0.024482 -5.352141 -0.131031
6,6   212  0.024140 -5.372413 -0.129692
4,4   188  0.021407 -5.545745 -0.118720
5,5   169  0.019244 -5.699454 -0.109680
3,5   167  0.019016 -5.716630 -0.108708
5,6   164  0.018675 -5.742782 -0.107244
6,5   159  0.018105 -5.787451 -0.104783
4,6   151  0.017194 -5.861929 -0.100792
6,4   138  0.015714 -5.991809 -0.094155
7,5   125  0.014234 -6.134550 -0.087317
2,3   112  0.012753 -6.292979 -0.080257
3,4   109  0.012412 -6.332149 -0.078593
8,5   106  0.012070 -6.372413 -0.076916
7,6   103  0.011729 -6.413833 -0.075225

In [96]:
Entropy4_5_1week = -1*entropy_4_5_1week['product'].sum()
Entropy4_5_1week

4.0294691154014863